Mads.isobs(Dict("a"=>1,"b"=>1), Dict("a"=>1))
Mads.isobs(Dict("a"=>1), Dict("a"=>1))
Mads.gettime(Dict("a"=>1))
Mads.settime!(Dict("a"=>1), 4)
Mads.settime!(Dict("a"=>1,"time"=>1), 4)
Mads.settime!(Dict("a"=>1,"t"=>1), 4)
Mads.setweight!(Dict("a"=>1), 4)
Mads.setweight!(Dict("a"=>1,"weight"=>1), 4)
Mads.setweight!(Dict("a"=>1,"w"=>15), 4)
Mads.settarget!(Dict("a"=>1), 4)
Mads.settarget!(Dict("a"=>1,"target"=>1), 4)
Mads.settarget!(Dict("a"=>1,"c"=>1), 4)
Mads.getobsdist(Dict("Observations"=>Dict("a"=>Dict())))
Mads.getobsdist(Dict("Observations"=>Dict("a"=>Dict("log"=>true))))
Mads.getobsdist(Dict("Observations"=>Dict("a"=>Dict())))
Mads.getobsmin(Dict("Observations"=>Dict("a"=>Dict("dist"=>"Uniform(14,15)"))))
Mads.getobsmax(Dict("Observations"=>Dict("a"=>Dict("dist"=>"Uniform(14,15)"))))
Mads.getweight(Dict("w"=>1))
Mads.getweight(Dict("a"=>1))