Mads.isparam(Dict("a"=>1,"b"=>1), Dict("a"=>1))
Mads.isparam(Dict("a"=>1), Dict("a"=>1))
Mads.getparamsmin(Dict("Parameters"=>Dict("a"=>Dict())))
Mads.getparamsmin(Dict("Parameters"=>Dict("a"=>Dict("log"=>true))))
Mads.getparamsmax(Dict("Parameters"=>Dict("a"=>Dict())))
Mads.getparamsmax(Dict("Parameters"=>Dict("a"=>Dict("log"=>true))))
Mads.getparamsinit_min(Dict("Parameters"=>Dict("a"=>Dict("log"=>true))))
Mads.getparamsinit_min(Dict("Parameters"=>Dict("a"=>Dict("init_min"=>14))))
Mads.getparamsinit_max(Dict("Parameters"=>Dict("a"=>Dict("log"=>true))))
Mads.getparamsinit_max(Dict("Parameters"=>Dict("a"=>Dict("init_min"=>14))))
Mads.getparamdistributions(Dict("Parameters"=>Dict("a"=>Dict("init_dist"=>"Uniform(14,15)"))), init_dist=true)
Mads.paramrand(Dict("Parameters"=>Dict("a"=>Dict("log"=>true, "dist"=>"Uniform(14,15)"))),"a")
Mads.paramrand(Dict("Parameters"=>Dict("a"=>Dict("log"=>true, "dist"=>"Normal(14,7)"))),"a")
Mads.void2nan!(Dict("a"=>Dict{Any,Any}("a"=>nothing)))
Mads.void2nan!(Dict("a"=>Dict{Any,Any}("a"=>Dict{Any,Any}("a"=>nothing))))
Mads.filterkeys(Dict("a"=>1), "a")
Mads.filterkeys(Dict("a"=>1), r"a")
Mads.getdictvalues(Dict("a"=>1), "a")
Mads.getdictvalues(Dict("a"=>1), r"a")