s = Array(Float64,2)
Mads.rosenbrock_gradient!(rand(2), s)
s = Array(Float64,2,2)
Mads.rosenbrock_hessian!(rand(2),s)
Mads.makerosenbrock(2)
Mads.makerosenbrock_gradient(2)
Mads.makepowell(2)
Mads.makepowell_gradient(2)
Mads.makesphere(2)
Mads.makesphere_gradient(2)
Mads.makedixonprice(2)
Mads.makedixonprice_gradient(2)
Mads.makesumsquares(2)
Mads.makesumsquares_gradient(2)
Mads.makerotatedhyperellipsoid(2)
Mads.makerotatedhyperellipsoid_gradient(2)