style = "default"
align_assignment = true
align_conditional = true
align_matrix = true
align_pair_arrow = true
align_struct_field = true
always_for_in = false
always_use_return = true
import_to_using = false
indent_submodule = true
indent = 4
join_lines_based_on_source = true
margin = 1000
remove_extra_newlines = true
normalize_line_endings = "unix"
surround_whereop_typeparameters = false
separate_kwargs_with_semicolon = true
trailing_comma = false
trailing_zero = false
whitespace_in_kwargs = false
whitespace_ops_in_indices = true
whitespace_typedefs = true