version: 2

# This project uses Julia + Documenter.jl (not Sphinx/MkDocs).
# We run a custom build and copy the generated HTML to $READTHEDOCS_OUTPUT.
build:
  os: ubuntu-24.04
  tools:
    python: "3.12"
  jobs:
    install:
      # Install Julia using 'jill' (Python).
      - python -m pip install --user --upgrade pip jill
      - python -m jill install 1.10.7 --confirm
      - ~/.local/bin/julia --version

      # Instantiate the docs environment.
      - ~/.local/bin/julia --project=docs -e 'using Pkg; Pkg.instantiate()'
    build:
      html:
        # Build docs (no deployment).
        - ~/.local/bin/julia --project=docs docs/make-rtd.jl

        # Publish to the location RTD expects.
        - mkdir -p $READTHEDOCS_OUTPUT/html/
        - cp -a docs/build/. $READTHEDOCS_OUTPUT/html/
